---

#Docker Installed version
docker_compose_version: 1.21.2
docker_ce_version: 18.03.1~ce-0~ubuntu

docker_registry: "{{ vault_docker_registry }}"
docker_user: "{{ vault_docker_user }}"
docker_pwd: "{{ vault_docker_pwd }}"
docker_email: "jenkins@sti.systems"
docker_log_driver: "journald"

#Docker Containers Deployed
pull_images: no

#Feature Flags
is_datadog_on_docker: True
is_swarm_mode_enabled: False
is_docker_prospector_enabled: False


etc_save_hosts:
    - name: "{{ ansible_ssh_host }}"
      ip: 127.0.0.1

# /etc/resolv.conf values
dns_resolv_searchpath:
  - 'dndc.intranet'

dns_server_list:
  - 10.250.29.3
  - 10.250.29.4
  - 8.8.8.8
  - 8.8.4.4

#Docker logs filebeat vars
docker_log_path: "/var/lib/docker/containers/*/*.log"
docker_container_log_name: "fon"

#System logs filebeat vars:
system_log_path: "/var/log/*.log"


###HAProxy
alfresco_host: "a-v-wt-fo-003.dndc.intranet"
alfresco_port: "8080"

keycloak_host: "a-v-wt-fo-001.dndc.intranet"
keycloak_port: "8080"

ui_host: "a-v-wt-fo-001.dndc.intranet"
ui_port: "4200"

